version: '2'
services:
  jenkins:
    image: jenkins/jenkins:2.346.2
    container_name: jenkins
    ports:
      - 8001:8080
      - 50000:50000
    restart: unless-stopped
    environment:
      - TZ=Asia/Kolkata
      - admin=Test105*
      - command:/bin/bash
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins-data:
    driver: local
